default: &default
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.hour
  autotrim: true
  silence_polling: true
  use_skip_locked: true
  trim_batch_size: 200
  reconnect_attempts: [0.1, 0.5, 1]

development:
  <<: *default

test:
  adapter: test

staging:
  <<: *default

production:
  <<: *default
